name: Checkmarx AST Scan
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@2.0.20 #Github Action version
        with:
          project_name: small-project
          base_uri: https://deu.ast.checkmarx.net/
          branch: ${{ github.head_ref }}
          cx_tenant: cx_ast_rd_galatica_canary
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
