name: Checkmarx AST Scan
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@2.0.20 #Github Action version
        with:
          project_name: small-project
          base_uri: https://ast.ppe.cxast.net/
          branch: ${{ github.head_ref }}
          cx_tenant: research_tenant
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
